
Import('env')
from utils.helper import *

# header files search path
cur_path = get_cur_path(env)
header_file_search_paths(env, [
	cur_path + "/inc",
])

srcs = [Glob('*.c') + Glob('*/*.c')]
obj = env.Object(srcs)
Return('obj')